spring.application.name=service-A
server.port = 8082
resilience4j.circuitbreaker.instances.serviceB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.serviceB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.serviceB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.serviceB.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.serviceB.minimumNumberOfCalls=5

resilience4j.retry.instances.serviceB.max-attempts=3
resilience4j.retry.instances.serviceB.wait-duration=2s

resilience4j.ratelimiter.instances.serviceB.limit-for-period=2
resilience4j.ratelimiter.instances.serviceB.limit-refresh-period=10s
resilience4j.ratelimiter.instances.serviceB.timeout-duration=0

eureka.instance.hostname=localhost