spring.application.name=SpringSecurity1
spring.datasource.url=jdbc:postgresql://localhost:5432/Sample
spring.datasource.username=postgres
spring.datasource.password=0000
server.servlet.session.cookie.same-site=strict
spring.jpa.hibernate.ddl-auto=update