spring.application.name=docker-exampleV2
spring.datasource.url=jdbc:postgresql://postgres:5432/Thambi 
spring.datasource.username=Hari
spring.datasource.password=3456
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
